function AboutPage({ t, S, C, setPage, lang }) {
  const STORY = {
    it: [
      "TUTTO È INIZIATO SU UNA SPIAGGIA.",
      "Eravamo in Repubblica Dominicana, davanti al mare, con una Presidente ghiacciata tra le mani. Quasi congelata, come si beve qui.",
      "Noi siamo Jonathan e Samuele, amici da oltre vent'anni.",
      "Quel giorno parlavamo del futuro e del paradiso che avevamo davanti agli occhi. Ci siamo chiesti se fosse possibile costruire qualcosa di nostro cercando, allo stesso tempo, un maggiore equilibrio con ciò che ci circondava.",
      "Meno rumore. Meno inquinamento. Un uso più intelligente dell'energia.",
      "La nostra passione per i golf cart e l'elettronica ha fatto il resto.",
      "Nel 2026 è nata TAAAC.",
      "NON VOLEVAMO SEMPLICEMENTE VENDERE GOLF CART.",
      "Volevamo cambiare il modo di sceglierli.",
      "Per questo, quando inizi a creare il tuo TAAAC, la prima cosa che ti chiediamo non è il colore.",
      "Ti chiediamo il suo nome.",
      "Da quel momento, ogni scelta porta la tua firma.",
      "Il colore. I posti. I sedili. Il volante. Le ruote.",
      "Tu lo immagini.",
      "Noi diamo forma alla tua idea.",
      "Abbiamo scelto motori e batterie pensando al giusto equilibrio tra prestazioni ed efficienza per la vita quotidiana nei Caraibi dominicani.",
      "E ogni TAAAC nasce con il pannello solare incluso.",
      "Perché sotto il sole dei Caraibi, per noi, aveva semplicemente senso.",
      "LA TAAAC FAMILY STA NASCENDO ADESSO.",
      "Non vogliamo che tutto finisca con una consegna.",
      "Vogliamo creare una famiglia di persone che possano incontrarsi, conoscersi e condividere esperienze.",
      "Forse nasceranno amicizie.",
      "Forse nuove storie.",
      "In fondo, anche TAAAC è nata così.",
      "Due amici…",
      "Una spiaggia…",
      "Una birra ghiacciata…",
      "Un'idea…",
      "Un progetto…",
      "Il prossimo capitolo?",
      "Lo scriviamo insieme…",
      "TAAAC",
      "Questa è la nostra storia.\nLa tua potrebbe essere appena iniziata.",
    ],
    en: [
      "IT ALL BEGAN ON A BEACH.",
      "We were in the Dominican Republic, facing the sea, an ice-cold Presidente in our hands. That's how it's meant to be enjoyed here.",
      "We're Jonathan and Samuele, friends for over twenty years.",
      "That day we talked about the future, and about the paradise right in front of us. We wondered if we could build something of our own while respecting the place that was giving us so much.",
      "Less noise. Less pollution. Energy used more intelligently.",
      "Our passion for golf carts and electronics did the rest.",
      "In 2026, TAAAC was born.",
      "WE DIDN'T WANT TO JUST SELL GOLF CARTS.",
      "We wanted to change the way people choose them.",
      "That's why, when you start creating your TAAAC, the first thing we ask isn't the color.",
      "We ask for its name.",
      "From that moment on, every choice carries your signature.",
      "The color. The seats. The upholstery. The wheel. The tires.",
      "You imagine it.",
      "We bring it to life.",
      "We chose motors and batteries built around the balance between performance and efficiency, for everyday life in the Dominican Caribbean.",
      "And every TAAAC is born with a solar panel included.",
      "Because under the Caribbean sun, for us, it simply made sense.",
      "THE TAAAC FAMILY IS JUST BEGINNING.",
      "We don't want it to end at delivery.",
      "We want to build a family of people who can meet, get to know each other, and share experiences.",
      "Maybe friendships will form.",
      "Maybe new stories.",
      "After all, that's exactly how TAAAC began too.",
      "Two friends…",
      "A beach…",
      "An ice-cold beer…",
      "An idea…",
      "A project…",
      "The next chapter?",
      "We're writing it together…",
      "TAAAC",
      "This is our story.\nYours might have just begun.",
    ],
    es: [
      "TODO EMPEZÓ EN UNA PLAYA.",
      "Estábamos en República Dominicana, frente al mar, con una Presidente bien fría en las manos. Casi congelada, como se toma aquí.",
      "Somos Jonathan y Samuele, amigos desde hace más de veinte años.",
      "Ese día hablábamos del futuro y del paraíso que teníamos delante. Nos preguntamos si era posible construir algo propio, cuidando al mismo tiempo el lugar que tanto nos estaba dando.",
      "Menos ruido. Menos contaminación. Energía usada con más inteligencia.",
      "Nuestra pasión por los golf carts y la electrónica hizo el resto.",
      "En 2026 nació TAAAC.",
      "NO QUERÍAMOS SOLO VENDER GOLF CARTS.",
      "Queríamos cambiar la forma de elegirlos.",
      "Por eso, cuando empiezas a crear tu TAAAC, lo primero que te preguntamos no es el color.",
      "Te preguntamos su nombre.",
      "Desde ese momento, cada elección lleva tu firma.",
      "El color. Los asientos. La tapicería. El volante. Las ruedas.",
      "Tú lo imaginas.",
      "Nosotros le damos forma.",
      "Elegimos motores y baterías pensando en el equilibrio entre rendimiento y eficiencia para el día a día en el Caribe dominicano.",
      "Y cada TAAAC nace con panel solar incluido.",
      "Porque bajo el sol del Caribe, para nosotros, simplemente tenía sentido.",
      "LA TAAAC FAMILY ESTÁ NACIENDO AHORA.",
      "No queremos que todo termine con una entrega.",
      "Queremos crear una familia de personas que se puedan encontrar, conocer y compartir experiencias.",
      "Tal vez nazcan amistades.",
      "Tal vez nuevas historias.",
      "Al final, así nació también TAAAC.",
      "Dos amigos…",
      "Una playa…",
      "Una cerveza bien fría…",
      "Una idea…",
      "Un proyecto…",
      "¿El próximo capítulo?",
      "Lo escribimos juntos…",
      "TAAAC",
      "Esta es nuestra historia.\nLa tuya podría estar empezando.",
    ],
    fr: [
      "TOUT A COMMENCÉ SUR UNE PLAGE.",
      "Nous étions en République Dominicaine, face à la mer, une Presidente glacée à la main. C'est ainsi qu'on la déguste ici.",
      "Nous sommes Jonathan et Samuele, amis depuis plus de vingt ans.",
      "Ce jour-là, nous parlions de l'avenir et du paradis qui s'offrait à nous. Nous nous sommes demandé s'il était possible de construire quelque chose à nous, tout en respectant davantage ce qui nous entourait.",
      "Moins de bruit. Moins de pollution. Une énergie utilisée plus intelligemment.",
      "Notre passion pour les golf carts et l'électronique a fait le reste.",
      "En 2026, TAAAC est né.",
      "NOUS NE VOULIONS PAS SIMPLEMENT VENDRE DES GOLF CARTS.",
      "Nous voulions changer la façon de les choisir.",
      "C'est pourquoi, lorsque tu commences à créer ton TAAAC, la première chose que nous te demandons n'est pas la couleur.",
      "Nous te demandons son nom.",
      "À partir de cet instant, chaque choix porte ta signature.",
      "La couleur. Les places. Les sièges. Le volant. Les roues.",
      "Tu l'imagines.",
      "Nous lui donnons forme.",
      "Nous avons choisi moteurs et batteries en pensant à l'équilibre entre performance et efficacité pour la vie quotidienne dans les Caraïbes dominicaines.",
      "Et chaque TAAAC naît avec un panneau solaire inclus.",
      "Parce que sous le soleil des Caraïbes, pour nous, cela avait tout simplement du sens.",
      "LA TAAAC FAMILY EST EN TRAIN DE NAÎTRE.",
      "Nous ne voulons pas que tout s'arrête à la livraison.",
      "Nous voulons créer une famille de personnes qui puissent se rencontrer, se connaître, partager des expériences.",
      "Peut-être naîtront des amitiés.",
      "Peut-être de nouvelles histoires.",
      "Après tout, c'est exactement comme ça que TAAAC est née, elle aussi.",
      "Deux amis…",
      "Une plage…",
      "Une bière bien fraîche…",
      "Une idée…",
      "Un projet…",
      "Le prochain chapitre ?",
      "Nous l'écrivons ensemble…",
      "TAAAC",
      "Voici notre histoire.\nLa tienne ne fait peut-être que commencer.",
    ],
    pl: [
      "WSZYSTKO ZACZĘŁO SIĘ NA PLAŻY.",
      "Byliśmy w Dominikanie, przed morzem, z lodowato zimną Presidente w dłoniach. Tak się ją tu pije.",
      "Jesteśmy Jonathan i Samuele, przyjaciółmi od ponad dwudziestu lat.",
      "Tego dnia rozmawialiśmy o przyszłości i o raju, który mieliśmy przed oczami. Zastanawialiśmy się, czy można zbudować coś swojego, jednocześnie bardziej szanując miejsce, które nam tyle dawało.",
      "Mniej hałasu. Mniej zanieczyszczeń. Mądrzejsze wykorzystanie energii.",
      "Nasza pasja do wózków golfowych i elektroniki zrobiła resztę.",
      "W 2026 roku narodziło się TAAAC.",
      "NIE CHCIELIŚMY PO PROSTU SPRZEDAWAĆ WÓZKÓW GOLFOWYCH.",
      "Chcieliśmy zmienić sposób ich wybierania.",
      "Dlatego, gdy zaczynasz tworzyć swój TAAAC, pierwszą rzeczą, o którą pytamy, nie jest kolor.",
      "Pytamy o jego imię.",
      "Od tego momentu każdy wybór niesie twój podpis.",
      "Kolor. Miejsca. Siedzenia. Kierownica. Koła.",
      "Ty to sobie wyobrażasz.",
      "My nadajemy temu kształt.",
      "Wybraliśmy silniki i baterie, myśląc o równowadze między osiągami a efektywnością w codziennym życiu na Dominikanie.",
      "A każdy TAAAC rodzi się z panelem słonecznym w zestawie.",
      "Bo pod karaibskim słońcem, dla nas, to po prostu miało sens.",
      "TAAAC FAMILY WŁAŚNIE SIĘ RODZI.",
      "Nie chcemy, żeby wszystko kończyło się na dostawie.",
      "Chcemy stworzyć rodzinę ludzi, którzy mogą się spotykać, poznawać i dzielić doświadczeniami.",
      "Może narodzą się przyjaźnie.",
      "Może nowe historie.",
      "W końcu, właśnie tak narodziło się też TAAAC.",
      "Dwóch przyjaciół…",
      "Plaża…",
      "Lodowato zimne piwo…",
      "Pomysł…",
      "Projekt…",
      "Następny rozdział?",
      "Piszemy go razem…",
      "TAAAC",
      "To jest nasza historia.\nTwoja może dopiero się zaczyna.",
    ],
    ru: [
      "ВСЁ НАЧАЛОСЬ НА ПЛЯЖЕ.",
      "Мы были в Доминиканской Республике, у моря, с ледяной Presidente в руках. Именно так её пьют здесь.",
      "Мы — Джонатан и Самуэле, друзья уже больше двадцати лет.",
      "В тот день мы говорили о будущем и о рае, который был перед нашими глазами. Мы задались вопросом: можно ли построить что-то своё, при этом бережнее относясь к месту, которое дало нам так много?",
      "Меньше шума. Меньше загрязнения. Более разумное использование энергии.",
      "Наша страсть к гольф-карам и электронике сделала остальное.",
      "В 2026 году родился TAAAC.",
      "МЫ НЕ ХОТЕЛИ ПРОСТО ПРОДАВАТЬ ГОЛЬФ-КАРЫ.",
      "Мы хотели изменить сам способ их выбора.",
      "Поэтому, когда ты начинаешь создавать свой TAAAC, первое, о чём мы спрашиваем — не цвет.",
      "Мы спрашиваем его имя.",
      "С этого момента каждый выбор несёт твою подпись.",
      "Цвет. Места. Сиденья. Руль. Колёса.",
      "Ты представляешь.",
      "Мы воплощаем.",
      "Мы выбрали моторы и батареи, думая о балансе между мощностью и эффективностью для повседневной жизни в доминиканских Карибах.",
      "И каждый TAAAC рождается с солнечной панелью в комплекте.",
      "Потому что под карибским солнцем для нас это просто имело смысл.",
      "TAAAC FAMILY ТОЛЬКО ЗАРОЖДАЕТСЯ.",
      "Мы не хотим, чтобы всё заканчивалось доставкой.",
      "Мы хотим создать семью людей, которые смогут встречаться, узнавать друг друга, делиться опытом.",
      "Может, родится дружба.",
      "Может, новые истории.",
      "В конце концов, именно так родился и сам TAAAC.",
      "Два друга…",
      "Пляж…",
      "Ледяное пиво…",
      "Идея…",
      "Проект…",
      "Следующая глава?",
      "Мы пишем её вместе…",
      "TAAAC",
      "Это наша история.\nТвоя, возможно, только начинается.",
    ],
  };

  const paragraphs = STORY[lang] || STORY.en;

  return (
    <div style={{...S.sec, maxWidth:720}}>
      <h1 style={{...S.title,textAlign:"center"}}>{t("About TAAAC Solutions – Electric Golf Carts in Bayahibe","TAAAC Solutions – Golf Carts Eléctricos en Bayahibe","TAAAC Solutions – Golf Cart Elettrici a Bayahibe")}</h1>
      {paragraphs.map((p, i) => {
        const isHeading = p === p.toUpperCase() && p.length > 4 && p !== "TAAAC";
        const isBrand = p === "TAAAC";
        if(isBrand) {
          return <div key={i} style={{textAlign:"center",color:C.gold,fontWeight:900,fontSize:"clamp(1.8rem,5vw,2.6rem)",letterSpacing:3,margin:"48px 0 20px"}}>{p}</div>;
        }
        if(isHeading) {
          return <h2 key={i} style={{...S.title,fontSize:"clamp(1.5rem,4.5vw,2.1rem)",marginTop:i===0?0:36,marginBottom:16,lineHeight:1.3}}>{p}</h2>;
        }
        return (
          <p key={i} style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14,whiteSpace:"pre-line"}}>{p}</p>
        );
      })}
      <div style={{textAlign:"center",marginTop:40}}>
        <button style={S.goldBtn} onClick={()=>setPage("home")}>🚗 {t("Create your TAAAC","Crea tu TAAAC","Crea il tuo TAAAC")}</button>
      </div>
    </div>
  );
}

export default AboutPage;
