import PropTypes from "prop-types";

function GuideChooseGolfCartPage({ t6, S, C, navigateTo }) {
  const faqs = [
    { q: t6("Which golf cart is best for a family?","¿Qué carrito de golf es mejor para una familia?","Quale golf cart è migliore per una famiglia?","Quel golf cart est le mieux adapté à une famille ?","Który wózek golfowy jest najlepszy dla rodziny?","Какой гольф-кар лучше всего подходит для семьи?"), a: t6("It mainly depends on the usual number of passengers, the route, and the space needed. For many families, a 4-seat cart is a versatile solution, while larger groups may prefer 6 seats.","Depende principalmente del número habitual de pasajeros, el recorrido y el espacio necesario. Para muchas familias un carrito de 4 plazas es una solución versátil, mientras que grupos más numerosos pueden valorar 6 plazas.","Dipende principalmente dal numero abituale di passeggeri, dal percorso e dallo spazio necessario. Per molte famiglie un golf cart da 4 posti è una soluzione versatile, mentre gruppi più numerosi possono valutare 6 posti.","Cela dépend principalement du nombre habituel de passagers, du trajet et de l'espace nécessaire. Pour de nombreuses familles, un golf cart 4 places est une solution polyvalente, tandis que les groupes plus nombreux peuvent privilégier 6 places.","Zależy głównie od zwykłej liczby pasażerów, trasy i potrzebnej przestrzeni. Dla wielu rodzin wózek 4-osobowy to wszechstronne rozwiązanie, podczas gdy większe grupy mogą rozważyć 6 miejsc.","Это зависит в первую очередь от обычного количества пассажиров, маршрута и необходимого пространства. Для многих семей гольф-кар на 4 места — универсальное решение, а более крупным группам может подойти вариант на 6 мест.") },
    { q: t6("Is a 48V or 72V golf cart better?","¿Es mejor un carrito de golf de 48V o 72V?","È meglio un golf cart da 48V o da 72V?","Vaut-il mieux un golf cart 48V ou 72V ?","Czy lepszy jest wózek golfowy 48V czy 72V?","Что лучше — гольф-кар на 48В или 72В?"), a: t6("Neither is automatically better. You need to consider the whole system: motor, controller, battery, load, terrain, and intended use.","Ninguno de los dos es automáticamente mejor. Hay que considerar el conjunto completo: motor, controlador, batería, carga, terreno y uso previsto.","Nessuno dei due è automaticamente migliore. Bisogna considerare l'insieme completo: motore, controller, batteria, carico, terreno e uso previsto.","Aucun des deux n'est automatiquement meilleur. Il faut considérer l'ensemble du système : moteur, contrôleur, batterie, charge, terrain et usage prévu.","Żaden z nich nie jest automatycznie lepszy. Trzeba wziąć pod uwagę cały system: silnik, kontroler, baterię, obciążenie, teren i planowane zastosowanie.","Ни один из вариантов не является автоматически лучше. Нужно учитывать всю систему целиком: двигатель, контроллер, батарею, нагрузку, местность и предполагаемое использование.") },
    { q: t6("Which battery is best for a golf cart?","¿Qué batería es mejor para un carrito de golf?","Quale batteria è migliore per un golf cart?","Quelle batterie est la meilleure pour un golf cart ?","Jaka bateria jest najlepsza do wózka golfowego?","Какая батарея лучше всего подходит для гольф-кара?"), a: t6("It depends on the budget, use, required range, and desired maintenance level. Lithium and lead-acid have different characteristics, and capacity, BMS, and charger should also be evaluated.","Depende del presupuesto, el uso, la autonomía necesaria y el mantenimiento deseado. Litio y plomo-ácido tienen características diferentes y también deben evaluarse la capacidad, el BMS y el cargador.","Dipende dal budget, dall'uso, dall'autonomia necessaria e dalla manutenzione desiderata. Litio e piombo-acido hanno caratteristiche diverse e vanno valutati anche capacità, BMS e caricatore.","Cela dépend du budget, de l'usage, de l'autonomie nécessaire et de l'entretien souhaité. Le lithium et le plomb-acide ont des caractéristiques différentes, et il faut aussi évaluer la capacité, le BMS et le chargeur.","Zależy od budżetu, sposobu użytkowania, wymaganego zasięgu i pożądanej konserwacji. Lit i kwas ołowiowy mają różne cechy, warto też ocenić pojemność, BMS i ładowarkę.","Это зависит от бюджета, использования, необходимого запаса хода и желаемого уровня обслуживания. Литий и свинцово-кислотные батареи имеют разные характеристики, также следует оценить ёмкость, BMS и зарядное устройство.") },
    { q: t6("How much range do I need?","¿Cuánta autonomía necesito?","Di quanta autonomia ho bisogno?","De combien d'autonomie ai-je besoin ?","Ile zasięgu potrzebuję?","Какой запас хода мне нужен?"), a: t6("It's best to start from the kilometers you'll actually travel each day and choose a configuration with margin, since weight, terrain, speed, and driving style all affect consumption.","Conviene partir de los kilómetros que realmente recorrerás cada día y elegir una configuración con margen, porque el peso, el terreno, la velocidad y el estilo de conducción influyen en el consumo.","Conviene partire dai chilometri che percorrerai realmente ogni giorno e scegliere una configurazione con margine, perché peso, terreno, velocità e stile di guida influenzano il consumo.","Il convient de partir des kilomètres que tu parcourras réellement chaque jour et de choisir une configuration avec une marge, car le poids, le terrain, la vitesse et le style de conduite influencent la consommation.","Warto zacząć od liczby kilometrów, które faktycznie będziesz pokonywać każdego dnia, i wybrać konfigurację z zapasem, ponieważ waga, teren, prędkość i styl jazdy wpływają na zużycie energii.","Стоит отталкиваться от того, сколько километров вы реально будете проезжать каждый день, и выбрать конфигурацию с запасом, поскольку вес, местность, скорость и стиль вождения влияют на расход энергии.") },
    { q: t6("What should I check before buying a golf cart?","¿Qué debo revisar antes de comprar un carrito de golf?","Cosa devo controllare prima di comprare un golf cart?","Que dois-je vérifier avant d'acheter un golf cart ?","Co powinienem sprawdzić przed zakupem wózka golfowego?","Что нужно проверить перед покупкой гольф-кара?"), a: t6("Battery, motor, brakes, tires, suspension, charger, warranty, available spare parts, and after-sales support.","Batería, motor, frenos, neumáticos, suspensión, cargador, garantía, repuestos disponibles y asistencia posventa.","Batteria, motore, freni, pneumatici, sospensioni, caricatore, garanzia, ricambi disponibili e assistenza post-vendita.","Batterie, moteur, freins, pneus, suspension, chargeur, garantie, pièces de rechange disponibles et service après-vente.","Baterię, silnik, hamulce, opony, zawieszenie, ładowarkę, gwarancję, dostępność części zamiennych i obsługę posprzedażową.","Батарею, двигатель, тормоза, шины, подвеску, зарядное устройство, гарантию, наличие запчастей и послепродажную поддержку.") },
  ];

  const linkStyle = {color:C.gold,textDecoration:"underline",cursor:"pointer",fontWeight:600};
  const seatBlocks = [
    {n:t6("2 Seats","2 plazas","2 Posti","2 Places","2 Miejsca","2 Места"), d:t6("Ideal for couples, personal use, and short trips.","Ideal para parejas, uso personal y pequeños desplazamientos.","Ideale per coppie, uso personale e piccoli spostamenti.","Idéal pour les couples, l'usage personnel et les petits trajets.","Idealny dla par, użytku osobistego i krótkich przejazdów.","Идеально для пар, личного использования и коротких поездок.")},
    {n:t6("4 Seats","4 plazas","4 Posti","4 Places","4 Miejsca","4 Места"), d:t6("A very versatile configuration for families, villa owners, and those who occasionally transport friends or guests.","Una configuración muy versátil para familias, propietarios de villas y quienes transportan ocasionalmente amigos o invitados.","Una configurazione molto versatile per famiglie, proprietari di ville e chi trasporta occasionalmente amici o ospiti.","Une configuration très polyvalente pour les familles, les propriétaires de villas et ceux qui transportent occasionnellement des amis ou des invités.","Bardzo wszechstronna konfiguracja dla rodzin, właścicieli willi i osób okazjonalnie przewożących przyjaciół lub gości.","Очень универсальная конфигурация для семей, владельцев вилл и тех, кто время от времени перевозит друзей или гостей.")},
    {n:t6("6 Seats","6 plazas","6 Posti","6 Places","6 Miejsc","6 Мест"), d:t6("Suitable for large families, groups, residences, hotels, resorts, and tourist activities.","Adecuado para familias numerosas, grupos, residencias, hoteles, resorts y actividades turísticas.","Adatto a famiglie numerose, gruppi, residenze, hotel, resort e attività turistiche.","Adapté aux familles nombreuses, aux groupes, aux résidences, aux hôtels, aux resorts et aux activités touristiques.","Odpowiedni dla licznych rodzin, grup, rezydencji, hoteli, resortów i atrakcji turystycznych.","Подходит для больших семей, групп, резиденций, отелей, курортов и туристических мероприятий.")},
  ];
  const needPairs = [
    [t6("Couple / daily use","Pareja / uso diario","Coppia / uso quotidiano","Couple / usage quotidien","Para / codzienne użytkowanie","Пара / ежедневное использование"),t6("Size, comfort, and range","Tamaño, confort y autonomía","Dimensioni, comfort e autonomia","Taille, confort et autonomie","Rozmiar, komfort i zasięg","Размер, комфорт и запас хода")],
    [t6("Family","Familia","Famiglia","Famille","Rodzina","Семья"),t6("4–6 seats, comfort, and capacity","4–6 plazas, confort y capacidad","4–6 posti, comfort e capacità","4 à 6 places, confort et capacité","4–6 miejsc, komfort i pojemność","4–6 мест, комфорт и вместимость")],
    [t6("Hotel / resort","Hotel / resort","Hotel / resort","Hôtel / resort","Hotel / resort","Отель / курорт"),t6("Capacity, reliability, and intensive use","Capacidad, fiabilidad y uso intensivo","Capacità, affidabilità e uso intensivo","Capacité, fiabilité et usage intensif","Pojemność, niezawodność i intensywne użytkowanie","Вместимость, надёжность и интенсивное использование")],
    [t6("Uneven terrain","Terreno irregular","Terreno irregolare","Terrain irrégulier","Nierówny teren","Неровная местность"),t6("Suspension, tires, and motor power","Suspensión, neumáticos y motorización","Sospensioni, pneumatici e motorizzazione","Suspension, pneus et motorisation","Zawieszenie, opony i napęd","Подвеска, шины и мощность двигателя")],
    [t6("Long routes","Recorridos largos","Percorsi lunghi","Longs trajets","Długie trasy","Длинные маршруты"),t6("Battery capacity and range","Capacidad de batería y autonomía","Capacità della batteria e autonomia","Capacité de la batterie et autonomie","Pojemność baterii i zasięg","Ёмкость батареи и запас хода")],
    [t6("Use near the sea","Uso cerca del mar","Uso vicino al mare","Usage près de la mer","Użytkowanie nad morzem","Использование у моря"),t6("Maintenance and protection","Mantenimiento y protección","Manutenzione e protezione","Entretien et protection","Konserwacja i ochrona","Обслуживание и защита")],
    [t6("Personalization","Personalización","Personalizzazione","Personnalisation","Personalizacja","Персонализация"),t6("Model, colors, and accessories","Modelo, colores y accesorios","Modello, colori e accessori","Modèle, couleurs et accessoires","Model, kolory i akcesoria","Модель, цвета и аксессуары")],
  ];

  return (
    <div style={{...S.sec, maxWidth:820}}>
      <h1 style={{...S.title,textAlign:"center"}}>{t6("How to Choose a Golf Cart in the Dominican Republic","Cómo Elegir un Carrito de Golf en República Dominicana","Come Scegliere un Golf Cart nella Repubblica Dominicana","Comment Choisir un Golf Cart en République Dominicaine","Jak Wybrać Wózek Golfowy w Dominikanie","Как Выбрать Гольф-кар в Доминиканской Республике")}</h1>

      {/* Introduzione */}
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("Choosing a golf cart isn't just about deciding which model or color you like best. The number of passengers, your daily route, the terrain, the battery, the power, and after-sales service can completely change which option is best for you.","Elegir un carrito de golf no consiste solamente en decidir qué modelo o color te gusta más. El número de pasajeros, el recorrido diario, el terreno, la batería, la potencia y el servicio posventa pueden cambiar completamente cuál es la mejor elección para ti.","Scegliere un golf cart non significa solo decidere quale modello o colore ti piace di più. Il numero di passeggeri, il percorso quotidiano, il terreno, la batteria, la potenza e l'assistenza post-vendita possono cambiare completamente quale sia la scelta migliore per te.","Choisir un golf cart ne consiste pas seulement à décider quel modèle ou quelle couleur te plaît le plus. Le nombre de passagers, ton trajet quotidien, le terrain, la batterie, la puissance et le service après-vente peuvent complètement changer quel est le meilleur choix pour toi.","Wybór wózka golfowego to nie tylko decyzja, jaki model czy kolor podoba ci się najbardziej. Liczba pasażerów, codzienna trasa, teren, bateria, moc i obsługa posprzedażowa mogą całkowicie zmienić, która opcja jest dla ciebie najlepsza.","Выбор гольф-кара — это не просто решение, какая модель или цвет вам больше нравится. Количество пассажиров, ежедневный маршрут, местность, батарея, мощность и послепродажное обслуживание могут полностью изменить, какой вариант подходит вам лучше всего.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("In the Dominican Republic, it's also worth considering local conditions: high temperatures, humidity, coastal areas, and different types of terrain.","En República Dominicana también conviene considerar las condiciones locales: temperaturas elevadas, humedad, zonas costeras y diferentes tipos de terreno.","Nella Repubblica Dominicana conviene anche considerare le condizioni locali: temperature elevate, umidità, zone costiere e diversi tipi di terreno.","En République Dominicaine, il convient également de prendre en compte les conditions locales : températures élevées, humidité, zones côtières et différents types de terrain.","W Dominikanie warto również uwzględnić lokalne warunki: wysokie temperatury, wilgotność, tereny nadmorskie i różne rodzaje nawierzchni.","В Доминиканской Республике также стоит учитывать местные условия: высокие температуры, влажность, прибрежные зоны и разные типы местности.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:32}}>
        {t6("This guide will help you understand the main aspects before buying a golf cart and choose a configuration suited to your needs.","Esta guía te ayudará a entender los aspectos principales antes de comprar un carrito de golf y a elegir una configuración adecuada para tus necesidades.","Questa guida ti aiuterà a comprendere gli aspetti principali prima di acquistare un golf cart e a scegliere una configurazione adatta alle tue esigenze.","Ce guide t'aidera à comprendre les principaux aspects avant d'acheter un golf cart et à choisir une configuration adaptée à tes besoins.","Ten poradnik pomoże ci zrozumieć najważniejsze aspekty przed zakupem wózka golfowego i wybrać konfigurację odpowiednią do twoich potrzeb.","Это руководство поможет вам понять основные аспекты перед покупкой гольф-кара и выбрать конфигурацию, подходящую именно вам.")}
      </p>

      {/* Sezione 1 */}
      <h2 style={S.title}>{t6("1. What Will You Use Your Golf Cart For?","1. ¿Para qué vas a utilizar tu carrito de golf?","1. Per Cosa Userai il Tuo Golf Cart?","1. À Quoi Va Servir Ton Golf Cart ?","1. Do Czego Będziesz Używać Wózka Golfowego?","1. Для Чего Вы Будете Использовать Гольф-кар?")}</h2>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:8}}>
        {t6("This should be the first decision.","Esta debería ser la primera decisión.","Questa dovrebbe essere la prima decisione.","Ce devrait être la première décision.","To powinna być pierwsza decyzja.","Это должно быть первое решение.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:16}}>
        {t6("A couple using it for small daily trips has different needs than a family of four, a villa, a residence, a hotel, or a tourist activity.","Una pareja que lo utiliza para pequeños desplazamientos diarios tiene necesidades diferentes a una familia de cuatro personas, una villa, una residencia, un hotel o una actividad turística.","Una coppia che lo utilizza per piccoli spostamenti quotidiani ha esigenze diverse da una famiglia di quattro persone, una villa, una residenza, un hotel o un'attività turistica.","Un couple qui l'utilise pour de petits déplacements quotidiens a des besoins différents d'une famille de quatre personnes, d'une villa, d'une résidence, d'un hôtel ou d'une activité touristique.","Para korzystająca z niego do krótkich codziennych przejazdów ma inne potrzeby niż rodzina czteroosobowa, willa, rezydencja, hotel czy atrakcja turystyczna.","У пары, использующей его для небольших ежедневных поездок, потребности отличаются от потребностей семьи из четырёх человек, виллы, резиденции, отеля или туристического объекта.")}
      </p>
      <div style={{color:C.muted,fontSize:14,lineHeight:2,marginBottom:20}}>
        {t6("How many people will normally travel?","¿Cuántas personas viajarán normalmente?","Quante persone viaggeranno normalmente?","Combien de personnes voyageront normalement ?","Ile osób będzie zwykle podróżować?","Сколько человек обычно будет ездить?")}<br/>
        {t6("About how many kilometers will you travel each day?","¿Cuántos kilómetros recorrerás aproximadamente cada día?","Quanti chilometri percorrerai approssimativamente ogni giorno?","Combien de kilomètres parcourras-tu environ chaque jour ?","Ile kilometrów będziesz pokonywać dziennie?","Сколько километров вы будете проезжать примерно каждый день?")}<br/>
        {t6("Will you drive mainly on asphalt or also on uneven terrain?","¿Circularás principalmente sobre asfalto o también sobre terrenos irregulares?","Circolerai principalmente su asfalto o anche su terreni irregolari?","Circuleras-tu principalement sur asphalte ou aussi sur des terrains irréguliers ?","Będziesz jeździć głównie po asfalcie, czy także po nierównym terenie?","Вы будете ездить в основном по асфальту или также по неровной местности?")}<br/>
        {t6("Do you need space for shopping, luggage, or other items?","¿Necesitas espacio para compras, equipaje u otros objetos?","Hai bisogno di spazio per la spesa, i bagagli o altri oggetti?","As-tu besoin d'espace pour les courses, les bagages ou d'autres objets ?","Czy potrzebujesz miejsca na zakupy, bagaż lub inne przedmioty?","Нужно ли вам место для покупок, багажа или других предметов?")}<br/>
        {t6("Will you use it occasionally or every day?","¿Lo utilizarás ocasionalmente o todos los días?","Lo userai occasionalmente o tutti i giorni?","L'utiliseras-tu occasionnellement ou tous les jours ?","Będziesz go używać okazjonalnie czy codziennie?","Вы будете использовать его время от времени или каждый день?")}
      </div>
      <div style={{...S.card(false), marginBottom:32, textAlign:"center"}}>
        <div style={{color:C.muted,fontSize:14,marginBottom:10}}>{t6("Not sure which one you need?","¿No sabes cuál necesitas?","Non sai quale ti serve?","Tu ne sais pas lequel te convient ?","Nie wiesz, którego potrzebujesz?","Не знаете, какой вам нужен?")}</div>
        <a href="/choose-your-golf-cart" onClick={(e)=>navigateTo("/choose-your-golf-cart", e)} style={{...S.goldBtn,textDecoration:"none",display:"inline-block"}}>{t6("DISCOVER YOUR TAAAC →","DESCUBRE TU TAAAC →","SCOPRI IL TUO TAAAC →","DÉCOUVRE TON TAAAC →","ODKRYJ SWÓJ TAAAC →","ОТКРОЙТЕ СВОЙ TAAAC →")}</a>
      </div>

      {/* Sezione 2 */}
      <h2 style={S.title}>{t6("2. 2, 4, or 6 Seats?","2. ¿2, 4 o 6 plazas?","2. 2, 4 o 6 Posti?","2. 2, 4 ou 6 Places ?","2. 2, 4 czy 6 Miejsc?","2. 2, 4 или 6 Мест?")}</h2>
      <div style={{...S.grid2, marginBottom:16}}>
        {seatBlocks.map(s=>(
          <div key={s.n} style={S.card(false)}>
            <div style={{color:C.gold,fontWeight:800,fontSize:15,marginBottom:6}}>{s.n}</div>
            <div style={{color:C.muted,fontSize:13,lineHeight:1.7}}>{s.d}</div>
          </div>
        ))}
      </div>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:16}}>
        {t6("Remember that more passengers also means more weight. That's why the number of seats should be considered together with the battery, motor, terrain, and intended use.","Recuerda que más pasajeros también significan más peso. Por eso, el número de plazas debe considerarse junto con la batería, el motor, el terreno y el uso previsto.","Ricorda che più passeggeri significano anche più peso. Per questo il numero di posti deve essere considerato insieme alla batteria, al motore, al terreno e all'uso previsto.","N'oublie pas que plus de passagers signifie aussi plus de poids. C'est pourquoi le nombre de places doit être considéré avec la batterie, le moteur, le terrain et l'usage prévu.","Pamiętaj, że więcej pasażerów oznacza też więcej wagi. Dlatego liczbę miejsc należy rozważać razem z baterią, silnikiem, terenem i planowanym zastosowaniem.","Помните, что больше пассажиров — это также больше веса. Поэтому количество мест следует учитывать вместе с батареей, двигателем, местностью и предполагаемым использованием.")}
      </p>
      <a href="/carrito-de-golf-2-4-o-6-plazas" onClick={(e)=>navigateTo("/carrito-de-golf-2-4-o-6-plazas", e)} style={{...linkStyle,display:"block",marginBottom:32}}>{t6("2, 4, or 6 Seats: Full Guide →","2, 4 o 6 plazas: guía completa →","2, 4 o 6 Posti: guida completa →","2, 4 ou 6 Places : guide complet →","2, 4 czy 6 Miejsc: pełny poradnik →","2, 4 или 6 Мест: полное руководство →")}</a>

      {/* Sezione 3 */}
      <h2 style={S.title}>{t6("3. Which Battery Should You Choose?","3. ¿Qué batería elegir?","3. Quale Batteria Scegliere?","3. Quelle Batterie Choisir ?","3. Jaką Baterię Wybrać?","3. Какую Батарею Выбрать?")}</h2>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("The battery determines a significant part of the range, weight, maintenance, and overall experience of an electric golf cart.","La batería determina una parte importante de la autonomía, el peso, el mantenimiento y la experiencia de uso de un carrito eléctrico.","La batteria determina una parte importante dell'autonomia, del peso, della manutenzione e dell'esperienza d'uso di un golf cart elettrico.","La batterie détermine une part importante de l'autonomie, du poids, de l'entretien et de l'expérience d'utilisation d'un golf cart électrique.","Bateria w dużej mierze decyduje o zasięgu, wadze, konserwacji i doświadczeniu użytkowania elektrycznego wózka golfowego.","Батарея во многом определяет запас хода, вес, обслуживание и общее впечатление от использования электрического гольф-кара.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("Traditional lead-acid batteries may have a lower initial cost, while modern lithium solutions can offer advantages in weight, maintenance, and energy management.","Las baterías tradicionales de plomo-ácido pueden tener un coste inicial inferior, mientras que las soluciones modernas de litio pueden ofrecer ventajas en peso, mantenimiento y gestión de la energía.","Le batterie tradizionali al piombo-acido possono avere un costo iniziale inferiore, mentre le moderne soluzioni al litio possono offrire vantaggi in termini di peso, manutenzione e gestione dell'energia.","Les batteries traditionnelles au plomb-acide peuvent avoir un coût initial inférieur, tandis que les solutions modernes au lithium peuvent offrir des avantages en poids, entretien et gestion de l'énergie.","Tradycyjne baterie kwasowo-ołowiowe mogą mieć niższy koszt początkowy, podczas gdy nowoczesne rozwiązania litowe mogą oferować przewagę pod względem wagi, konserwacji i zarządzania energią.","Традиционные свинцово-кислотные батареи могут иметь более низкую первоначальную стоимость, тогда как современные литиевые решения могут предложить преимущества по весу, обслуживанию и управлению энергией.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:16}}>
        {t6("However, not all batteries are the same. Besides the technology, it's worth evaluating its capacity, the BMS system, the compatible charger, and the manufacturer's specifications.","Sin embargo, no todas las baterías son iguales. Además de la tecnología, conviene evaluar su capacidad, el sistema BMS, el cargador compatible y las especificaciones del fabricante.","Tuttavia, non tutte le batterie sono uguali. Oltre alla tecnologia, conviene valutare la capacità, il sistema BMS, il caricatore compatibile e le specifiche del produttore.","Cependant, toutes les batteries ne se valent pas. Au-delà de la technologie, il convient d'évaluer sa capacité, le système BMS, le chargeur compatible et les spécifications du fabricant.","Jednak nie wszystkie baterie są takie same. Oprócz technologii warto ocenić jej pojemność, system BMS, kompatybilną ładowarkę oraz specyfikacje producenta.","Однако не все батареи одинаковы. Помимо технологии, стоит оценить её ёмкость, систему BMS, совместимое зарядное устройство и характеристики производителя.")}
      </p>
      <a href="/bateria-litio-vs-plomo-carrito-de-golf" onClick={(e)=>navigateTo("/bateria-litio-vs-plomo-carrito-de-golf", e)} style={{...linkStyle,display:"block",marginBottom:32}}>{t6("Lithium vs Lead: Full Guide →","Litio vs plomo: guía completa →","Litio vs piombo: guida completa →","Lithium vs plomb : guide complet →","Lit kontra ołów: pełny poradnik →","Литий против свинца: полное руководство →")}</a>

      {/* Sezione 4 */}
      <h2 style={S.title}>{t6("4. 48V or 72V?","4. ¿48V o 72V?","4. 48V o 72V?","4. 48V ou 72V ?","4. 48V czy 72V?","4. 48В или 72В?")}</h2>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("It's easy to think a 72V cart is always better than a 48V one, but that's not necessarily the case.","Es fácil pensar que un carrito de 72V siempre es mejor que uno de 48V, pero no necesariamente es así.","È facile pensare che un golf cart da 72V sia sempre migliore di uno da 48V, ma non è necessariamente così.","Il est facile de penser qu'un golf cart de 72V est toujours meilleur qu'un de 48V, mais ce n'est pas nécessairement le cas.","Łatwo pomyśleć, że wózek 72V jest zawsze lepszy niż 48V, ale niekoniecznie tak jest.","Легко подумать, что гольф-кар на 72В всегда лучше, чем на 48В, но это не обязательно так.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("Voltage is part of a complete system. Motor, controller, battery capacity, weight, number of passengers, wheels, and terrain also influence the vehicle's behavior.","El voltaje forma parte de un sistema completo. Motor, controlador, capacidad de la batería, peso, número de pasajeros, ruedas y terreno también influyen en el comportamiento del vehículo.","Il voltaggio fa parte di un sistema completo. Motore, controller, capacità della batteria, peso, numero di passeggeri, ruote e terreno influenzano anch'essi il comportamento del veicolo.","La tension fait partie d'un système complet. Le moteur, le contrôleur, la capacité de la batterie, le poids, le nombre de passagers, les roues et le terrain influencent également le comportement du véhicule.","Napięcie jest częścią całego systemu. Silnik, kontroler, pojemność baterii, waga, liczba pasażerów, koła i teren również wpływają na zachowanie pojazdu.","Напряжение — лишь часть общей системы. Двигатель, контроллер, ёмкость батареи, вес, количество пассажиров, колёса и местность также влияют на поведение транспортного средства.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("A higher-voltage system can be interesting for heavier-load or more demanding applications, but for many everyday uses, a properly sized 48V system can be perfectly adequate.","Un sistema de mayor voltaje puede ser interesante en aplicaciones de mayor carga o exigencia, pero para muchos usos cotidianos un sistema correctamente dimensionado de 48V puede ser perfectamente adecuado.","Un sistema a tensione maggiore può essere interessante per applicazioni con carichi maggiori o più esigenti, ma per molti usi quotidiani un sistema da 48V correttamente dimensionato può essere perfettamente adeguato.","Un système à tension plus élevée peut être intéressant pour des applications à charge plus lourde ou plus exigeantes, mais pour de nombreux usages quotidiens, un système 48V correctement dimensionné peut être parfaitement adapté.","System o wyższym napięciu może być interesujący w zastosowaniach wymagających większego obciążenia, ale do wielu codziennych zastosowań odpowiednio dobrany system 48V może być całkowicie wystarczający.","Система с более высоким напряжением может быть интересна для более тяжёлых нагрузок или требовательных применений, но для многих повседневных задач правильно подобранная система 48В может быть вполне достаточной.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:16}}>
        {t6("That's why the choice shouldn't be based solely on the highest number, but on how the entire vehicle is configured.","Por eso, la elección no debería basarse solamente en el número más alto, sino en cómo está configurado todo el vehículo.","Per questo la scelta non dovrebbe basarsi solo sul numero più alto, ma su come è configurato l'intero veicolo.","C'est pourquoi le choix ne devrait pas se baser uniquement sur le chiffre le plus élevé, mais sur la façon dont l'ensemble du véhicule est configuré.","Dlatego wybór nie powinien opierać się wyłącznie na najwyższej liczbie, ale na tym, jak skonfigurowany jest cały pojazd.","Поэтому выбор не должен основываться только на самом высоком числе, а на том, как настроено всё транспортное средство в целом.")}
      </p>
      <a href="/48v-vs-72v-carrito-de-golf" onClick={(e)=>navigateTo("/48v-vs-72v-carrito-de-golf", e)} style={{...linkStyle,display:"block",marginBottom:32}}>{t6("48V vs 72V: Full Guide →","48V vs 72V: guía completa →","48V vs 72V: guida completa →","48V vs 72V : guide complet →","48V vs 72V: pełny poradnik →","48В против 72В: полное руководство →")}</a>

      {/* Sezione 5 */}
      <h2 style={S.title}>{t6("5. Think About the Terrain","5. Piensa en el terreno","5. Pensa al Terreno","5. Pense au Terrain","5. Pomyśl o Terenie","5. Подумайте о Местности")}</h2>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("Where you'll use your cart should also influence your choice.","El lugar donde utilizarás tu carrito también debe influir en la elección.","Anche il luogo in cui utilizzerai il tuo golf cart deve influenzare la scelta.","L'endroit où tu utiliseras ton golf cart doit aussi influencer ton choix.","Miejsce, w którym będziesz używać wózka, również powinno wpływać na wybór.","Место, где вы будете использовать свой гольф-кар, также должно влиять на выбор.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("For trips mainly on regular surfaces, comfort and efficiency may be the priority.","Para desplazamientos principalmente sobre superficies regulares pueden ser prioritarios el confort y la eficiencia.","Per spostamenti principalmente su superfici regolari possono essere prioritari il comfort e l'efficienza.","Pour des déplacements principalement sur des surfaces régulières, le confort et l'efficacité peuvent être prioritaires.","Do przejazdów głównie po równych nawierzchniach priorytetem może być komfort i efektywność.","Для поездок в основном по ровным поверхностям приоритетом может быть комфорт и эффективность.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("For more uneven terrain, slopes, or more demanding uses, it's worth paying closer attention to tires, suspension, ground clearance, motor, and overall configuration.","Para terrenos más irregulares, pendientes o usos más exigentes, conviene prestar mayor atención a neumáticos, suspensión, altura libre, motor y configuración general.","Per terreni più irregolari, pendenze o usi più impegnativi, conviene prestare maggiore attenzione a pneumatici, sospensioni, altezza da terra, motore e configurazione generale.","Pour des terrains plus irréguliers, des pentes ou des usages plus exigeants, il convient de prêter davantage attention aux pneus, à la suspension, à la garde au sol, au moteur et à la configuration générale.","W przypadku bardziej nierównego terenu, wzniesień lub bardziej wymagających zastosowań warto zwrócić większą uwagę na opony, zawieszenie, prześwit, silnik i ogólną konfigurację.","Для более неровной местности, склонов или более требовательного использования стоит уделить больше внимания шинам, подвеске, дорожному просвету, двигателю и общей конфигурации.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:32}}>
        {t6("In the Dominican Republic, needs can differ between a residence in Bayahibe, a property in Dominicus, a resort in Punta Cana, or a private community with longer routes.","En República Dominicana, las necesidades pueden ser diferentes entre una residencia en Bayahibe, una propiedad en Dominicus, un resort en Punta Cana o una comunidad privada con recorridos más largos.","Nella Repubblica Dominicana, le esigenze possono essere diverse tra una residenza a Bayahibe, una proprietà a Dominicus, un resort a Punta Cana o una comunità privata con percorsi più lunghi.","En République Dominicaine, les besoins peuvent différer entre une résidence à Bayahibe, une propriété à Dominicus, un resort à Punta Cana ou une communauté privée avec des trajets plus longs.","W Dominikanie potrzeby mogą się różnić między rezydencją w Bayahibe, nieruchomością w Dominicus, resortem w Punta Cana a prywatnym osiedlem z dłuższymi trasami.","В Доминиканской Республике потребности могут отличаться в зависимости от того, идёт ли речь о резиденции в Баяибе, собственности в Доминикусе, курорте в Пунта-Кане или частном комплексе с более длинными маршрутами.")}
      </p>

      {/* Sezione 6 */}
      <h2 style={S.title}>{t6("6. The Climate Matters Too","6. El clima también importa","6. Anche il Clima è Importante","6. Le Climat Compte Aussi","6. Klimat Też Ma Znaczenie","6. Климат Тоже Важен")}</h2>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("Heat, humidity, and the coastal environment are factors worth considering.","El calor, la humedad y el ambiente costero son factores que conviene considerar.","Il caldo, l'umidità e l'ambiente costiero sono fattori da considerare.","La chaleur, l'humidité et l'environnement côtier sont des facteurs à prendre en compte.","Upał, wilgotność i środowisko nadmorskie to czynniki, które warto wziąć pod uwagę.","Жара, влажность и прибрежная среда — факторы, которые стоит учитывать.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("For the battery, it's important to respect the operating and charging temperatures specified by the manufacturer and to use a suitable charger.","En la batería es importante respetar las temperaturas de funcionamiento y carga indicadas por el fabricante y utilizar un cargador adecuado.","Per la batteria è importante rispettare le temperature di funzionamento e ricarica indicate dal produttore e utilizzare un caricatore adeguato.","Pour la batterie, il est important de respecter les températures de fonctionnement et de charge indiquées par le fabricant et d'utiliser un chargeur adapté.","W przypadku baterii ważne jest przestrzeganie temperatur pracy i ładowania wskazanych przez producenta oraz stosowanie odpowiedniej ładowarki.","Для батареи важно соблюдать рабочие температуры и температуры зарядки, указанные производителем, и использовать подходящее зарядное устройство.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:16}}>
        {t6("In areas near the sea, it's also worth paying attention to the maintenance of connections and exposed metal components, due to the salty environment.","En zonas próximas al mar también conviene prestar atención al mantenimiento de conexiones y componentes metálicos expuestos, debido al ambiente salino.","Nelle zone vicine al mare conviene anche prestare attenzione alla manutenzione delle connessioni e dei componenti metallici esposti, a causa dell'ambiente salino.","Dans les zones proches de la mer, il convient également de prêter attention à l'entretien des connexions et des composants métalliques exposés, en raison de l'environnement salin.","W obszarach blisko morza warto również zwrócić uwagę na konserwację połączeń i odsłoniętych elementów metalowych ze względu na słone środowisko.","В районах вблизи моря также стоит уделить внимание обслуживанию соединений и открытых металлических компонентов из-за солёной среды.")}
      </p>
      <a href="/mantenimiento-carrito-de-golf-cerca-del-mar" onClick={(e)=>navigateTo("/mantenimiento-carrito-de-golf-cerca-del-mar", e)} style={{...linkStyle,display:"block",marginBottom:32}}>{t6("How to Care for a Golf Cart Near the Sea: Full Guide →","Cómo cuidar un carrito de golf cerca del mar: guía completa →","Come curare un golf cart vicino al mare: guida completa →","Comment entretenir un golf cart près de la mer : guide complet →","Jak dbać o wózek golfowy nad morzem: pełny poradnik →","Как ухаживать за гольф-каром у моря: полное руководство →")}</a>

      {/* Sezione 7 */}
      <h2 style={S.title}>{t6("7. Range: Don't Rely Only on the Advertised Number","7. Autonomía: no te quedes solo con el número anunciado","7. Autonomia: non fermarti solo al numero dichiarato","7. Autonomie : ne te fie pas seulement au chiffre annoncé","7. Zasięg: nie polegaj tylko na podanej liczbie","7. Запас хода: не полагайтесь только на заявленное число")}</h2>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("The range stated by a manufacturer is a reference, not a guarantee that every user will travel exactly the same distance.","La autonomía indicada por un fabricante es una referencia, no una garantía de que todos los usuarios recorrerán exactamente la misma distancia.","L'autonomia indicata da un produttore è un riferimento, non una garanzia che tutti gli utenti percorreranno esattamente la stessa distanza.","L'autonomie indiquée par un fabricant est une référence, pas une garantie que tous les utilisateurs parcourront exactement la même distance.","Zasięg podawany przez producenta jest wartością orientacyjną, a nie gwarancją, że każdy użytkownik pokona dokładnie taki sam dystans.","Заявленный производителем запас хода — это ориентир, а не гарантия того, что каждый пользователь проедет ровно такое же расстояние.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:14}}>
        {t6("Passengers, weight, speed, slopes, tires, accessories, temperature, and driving style can all affect consumption.","Pasajeros, peso, velocidad, pendientes, neumáticos, accesorios, temperatura y estilo de conducción pueden modificar el consumo.","Passeggeri, peso, velocità, pendenze, pneumatici, accessori, temperatura e stile di guida possono modificare il consumo.","Passagers, poids, vitesse, pentes, pneus, accessoires, température et style de conduite peuvent modifier la consommation.","Pasażerowie, waga, prędkość, wzniesienia, opony, akcesoria, temperatura i styl jazdy mogą wpływać na zużycie energii.","Пассажиры, вес, скорость, уклоны, шины, аксессуары, температура и стиль вождения могут влиять на расход энергии.")}
      </p>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:32}}>
        {t6("That's why it's better to calculate how many kilometers you actually need each day and keep a safety margin.","Por eso es mejor calcular cuántos kilómetros necesitas realmente cada día y mantener un margen de seguridad.","Per questo è meglio calcolare quanti chilometri ti servono realmente ogni giorno e mantenere un margine di sicurezza.","C'est pourquoi il est préférable de calculer combien de kilomètres tu as réellement besoin chaque jour et de garder une marge de sécurité.","Dlatego lepiej obliczyć, ile kilometrów naprawdę potrzebujesz każdego dnia, i zachować margines bezpieczeństwa.","Поэтому лучше рассчитать, сколько километров вам реально нужно каждый день, и оставить запас.")}
      </p>

      {/* Sezione 8 */}
      <h2 style={S.title}>{t6("8. Don't Buy Based on Price Alone","8. No compres solamente por precio","8. Non comprare solo in base al prezzo","8. N'achète pas uniquement en fonction du prix","8. Nie kupuj wyłącznie na podstawie ceny","8. Не покупайте, ориентируясь только на цену")}</h2>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:8}}>
        {t6("Before buying, it's worth asking yourself:","Antes de comprar, conviene preguntarse:","Prima di comprare, conviene chiedersi:","Avant d'acheter, il convient de te demander :","Przed zakupem warto zadać sobie pytanie:","Перед покупкой стоит задать себе вопрос:")}
      </p>
      <div style={{color:C.muted,fontSize:14,lineHeight:2,marginBottom:16}}>
        {t6("What warranty does it have?","¿Qué garantía tiene?","Che garanzia ha?","Quelle garantie offre-t-il ?","Jaką ma gwarancję?","Какая на него гарантия?")}<br/>
        {t6("Are spare parts available?","¿Hay repuestos disponibles?","Ci sono ricambi disponibili?","Y a-t-il des pièces de rechange disponibles ?","Czy dostępne są części zamienne?","Доступны ли запчасти?")}<br/>
        {t6("Who will carry out the maintenance?","¿Quién realizará el mantenimiento?","Chi si occuperà della manutenzione?","Qui effectuera l'entretien ?","Kto będzie wykonywać konserwację?","Кто будет проводить обслуживание?")}<br/>
        {t6("What battery does it use?","¿Qué batería utiliza?","Che batteria utilizza?","Quelle batterie utilise-t-il ?","Jakiej baterii używa?","Какая батарея используется?")}<br/>
        {t6("What charger does it include?","¿Qué cargador incluye?","Che caricatore include?","Quel chargeur inclut-il ?","Jaką ładowarkę zawiera?","Какое зарядное устройство входит в комплект?")}<br/>
        {t6("Is there support available after the purchase?","¿Existe asistencia después de la compra?","C'è assistenza dopo l'acquisto?","Existe-t-il une assistance après l'achat ?","Czy dostępne jest wsparcie po zakupie?","Есть ли поддержка после покупки?")}<br/>
        {t6("What exactly does the price include?","¿Qué incluye exactamente el precio?","Cosa include esattamente il prezzo?","Que comprend exactement le prix ?","Co dokładnie obejmuje cena?","Что именно включено в цену?")}
      </div>
      <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:16}}>
        {t6("A golf cart doesn't end the day you buy it. The availability of support, maintenance, and spare parts is also part of a good choice.","Un carrito de golf no termina el día de la compra. La disponibilidad de asistencia, mantenimiento y repuestos también forma parte de una buena elección.","Un golf cart non finisce il giorno dell'acquisto. La disponibilità di assistenza, manutenzione e ricambi fa anch'essa parte di una buona scelta.","Un golf cart ne s'arrête pas le jour de l'achat. La disponibilité de l'assistance, de l'entretien et des pièces de rechange fait aussi partie d'un bon choix.","Wózek golfowy nie kończy się w dniu zakupu. Dostępność wsparcia, konserwacji i części zamiennych to również część dobrego wyboru.","Гольф-кар не заканчивается в день покупки. Доступность поддержки, обслуживания и запчастей — тоже часть хорошего выбора.")}
      </p>
      <a href="/que-revisar-antes-de-comprar-carrito-de-golf" onClick={(e)=>navigateTo("/que-revisar-antes-de-comprar-carrito-de-golf", e)} style={{...linkStyle,display:"block",marginBottom:32}}>{t6("What to Check Before Buying a Golf Cart: Full Checklist →","Qué revisar antes de comprar un carrito de golf: checklist completa →","Cosa controllare prima di comprare un golf cart: checklist completa →","Que vérifier avant d'acheter un golf cart : checklist complète →","Co sprawdzić przed zakupem wózka golfowego: pełna checklista →","Что проверить перед покупкой гольф-кара: полный чек-лист →")}</a>

      {/* Sezione 9 */}
      <h2 style={S.title}>{t6("9. Choose Based on Your Needs, Not Trends","9. Elige según tus necesidades, no según la moda","9. Scegli in base alle tue esigenze, non alla moda","9. Choisis selon tes besoins, pas selon la mode","9. Wybieraj na podstawie potrzeb, nie mody","9. Выбирайте по своим потребностям, а не по моде")}</h2>
      <div style={{marginBottom:32}}>
        {needPairs.map(([need,rec])=>(
          <div key={need} style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap",padding:"10px 0",borderBottom:"1px solid #222"}}>
            <div style={{color:C.white,fontWeight:700,fontSize:14}}>{need}</div>
            <div style={{color:C.muted,fontSize:14,textAlign:"right"}}>{rec}</div>
          </div>
        ))}
      </div>

      {/* CTA finale */}
      <div style={{textAlign:"center",borderTop:"1px solid #222",paddingTop:32,marginBottom:32}}>
        <h2 style={{...S.title,fontSize:"clamp(1.4rem,4vw,1.9rem)"}}>{t6("Still not sure which cart to choose?","¿Todavía no sabes qué carrito elegir?","Non sai ancora quale golf cart scegliere?","Tu ne sais toujours pas quel golf cart choisir ?","Nadal nie wiesz, który wózek wybrać?","Всё ещё не знаете, какой гольф-кар выбрать?")}</h2>
        <p style={{color:C.muted,fontSize:15,lineHeight:1.8,marginBottom:16}}>
          {t6("You don't need to be an expert in batteries, motors, or voltages to get started. Tell us how you want to use your golf cart and we'll help you find the best option.","No necesitas ser un experto en baterías, motores o voltajes para empezar. Cuéntanos cómo quieres utilizar tu carrito de golf y te ayudaremos a encontrar la opción más adecuada.","Non devi essere un esperto di batterie, motori o voltaggi per iniziare. Raccontaci come vuoi utilizzare il tuo golf cart e ti aiuteremo a trovare l'opzione più adatta.","Tu n'as pas besoin d'être un expert en batteries, moteurs ou tensions pour commencer. Dis-nous comment tu souhaites utiliser ton golf cart et nous t'aiderons à trouver l'option la plus adaptée.","Nie musisz być ekspertem od baterii, silników czy napięć, żeby zacząć. Powiedz nam, jak chcesz używać swojego wózka golfowego, a pomożemy ci znaleźć najlepszą opcję.","Вам не нужно быть экспертом по батареям, двигателям или напряжению, чтобы начать. Расскажите нам, как вы хотите использовать свой гольф-кар, и мы поможем найти наиболее подходящий вариант.")}
        </p>
        <div style={{display:"flex",flexWrap:"wrap",gap:12,justifyContent:"center",marginBottom:16}}>
          <a href="/choose-your-golf-cart" onClick={(e)=>navigateTo("/choose-your-golf-cart", e)} style={{...S.goldBtn,textDecoration:"none",display:"inline-block"}}>{t6("FIND YOUR TAAAC →","ENCUENTRA TU TAAAC →","TROVA IL TUO TAAAC →","TROUVE TON TAAAC →","ZNAJDŹ SWÓJ TAAAC →","НАЙДИТЕ СВОЙ TAAAC →")}</a>
          <a href="/configurator" onClick={(e)=>navigateTo("/configurator", e)} style={{...S.outBtn,textDecoration:"none",display:"inline-block"}}>{t6("CONFIGURE YOUR CART →","CONFIGURA TU CARRITO →","CONFIGURA IL TUO GOLF CART →","CONFIGURE TON GOLF CART →","SKONFIGURUJ SWÓJ WÓZEK →","НАСТРОЙТЕ СВОЙ ГОЛЬФ-КАР →")}</a>
        </div>
        <a href="/golf-carts-dominican-republic" onClick={(e)=>navigateTo("/golf-carts-dominican-republic", e)} style={linkStyle}>{t6("See Our Golf Carts in the Dominican Republic →","Ver nuestros carritos de golf en República Dominicana →","Guarda i nostri golf cart nella Repubblica Dominicana →","Voir nos golf carts en République Dominicaine →","Zobacz nasze wózki golfowe w Dominikanie →","Посмотреть наши гольф-кары в Доминиканской Республике →")}</a>
      </div>

      {/* FAQ */}
      <h2 style={S.title}>{t6("Frequently Asked Questions","Preguntas Frecuentes","Domande Frequenti","Questions Fréquentes","Najczęściej Zadawane Pytania","Часто Задаваемые Вопросы")}</h2>
      <div style={{marginBottom:16}}>
        {faqs.map((f,i)=>(
          <div key={i} style={{marginBottom:20}}>
            <div style={{color:C.gold,fontWeight:700,fontSize:14,marginBottom:6}}>{f.q}</div>
            <div style={{color:C.muted,fontSize:14,lineHeight:1.7}}>{f.a}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

GuideChooseGolfCartPage.propTypes = {
  t6: PropTypes.func.isRequired,
  S: PropTypes.object.isRequired,
  C: PropTypes.object.isRequired,
  navigateTo: PropTypes.func.isRequired,
};

export default GuideChooseGolfCartPage;
